# Generated by Django 4.1.7 on 2023-03-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementals_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('elements', models.ManyToManyField(blank=True, to='elementals_app.element')),
                ('entities', models.ManyToManyField(blank=True, to='elementals_app.entity')),
            ],
        ),
    ]
