# Generated by Django 4.1.7 on 2023-03-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementals_app', '0002_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='elements',
        ),
        migrations.AddField(
            model_name='player',
            name='hand',
            field=models.ManyToManyField(blank=True, related_name='players_holding', to='elementals_app.element'),
        ),
    ]
